version: 2.1

orbs:
  node: circleci/node@4.9.0
  docker: circleci/docker@0.5.19
  
jobs:
  tests:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - node/install:
          node-version: latest
      - run: ./create-version-file.sh
      - run: ./docker-build.sh
      - node/install-packages
      - run: npm run compose
      - run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm test # repetition this is intentional
      - run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm test # repetition this is intentional
      - run: ./.circleci/release-to-staging.sh

workflows:
  version: 2
  build:
    jobs:
      - tests:
          filters:
            branches:
              only: /.*/
            tags:
              only: /v.*/
