version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  tests:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - node/install:
          node-version: latest
      - run: ./create-version-file.sh
      - run: ./docker-build.sh
      - node/install-packages
      - run: npm run compose
      - run:
        command: npm test
        environment:
          NODE_OPTIONS: --openssl-legacy-provider
      - run:
        command: npm test # repetition this is intentional
        environment:
          NODE_OPTIONS: --openssl-legacy-provider
      - run: ./.circleci/release-to-staging.sh

workflows:
  version: 2
  build:
    jobs:
      - tests:
          filters:
            branches:
              only: /.*/
            tags:
              only: /v.*/
