version: 2.1

orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@0.5.19

jobs:
  tests:
    machine:
      image: ubuntu:16.04
      docker_layer_caching: true
    steps:
      - checkout
      - run: ./create-version-file.sh
      - docker/install-docker      
      - run: ./docker-build.sh
      - node/install-packages
      - run: npm run compose
      - run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm test # repetition this is intentional
      - run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm test # repetition this is intentional
      - run: ./.circleci/release-to-staging.sh

workflows:
  version: 2
  build:
    jobs:
      - tests:
          filters:
            branches:
              only: /.*/
            tags:
              only: /v.*/
