version: 2
jobs:
  tests:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run: ./create-version-file.sh
      - run: ./docker-build.sh

workflows:
  version: 2
  build:
    jobs:
      - tests