version: 2
jobs:
  tests:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run: ./create-version-file.sh
      # - run: ./docker-build.sh
      - run: npm install
      - run: npm run compose
      - run: npm test
      - run: ./.circleci/release-to-staging.sh

workflows:
  version: 2
  build:
    jobs:
      - tests
