name: Build and Test
on:
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.20.4
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.4
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./... -v

      - run: ./docker-build.sh
      - name: release-to-docker-hub-staging
        env:
          DOCKER_HUB_IMAGE_PATH: orbsnetworkstaging/signer
          DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_STAGING_LOGIN }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_STAGING_PASSWORD }}
        run: ./.github/release-to-staging.sh